version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
      - image: circleci/android:api-28
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: "Install Ionic and Cordova"
          command: |
            sudo npm install -g ionic cordova yarn
      - run:
          name: "Add android platform"
          command: |
            mkdir www
            ionic cordova platform add android -Y --noresources
            ionic config set -g telemetry true
            cordova telemetry on
      - run:
          name: "Generate APK"
          command: |
            yarn install
            ionic cordova build android -Y
            cp -r platforms/android/build/outputs/apk $CIRCLE_ARTIFACTS

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build